version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4096M
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512M
volumes:
  redis_volume_data:
  redis_insight_volume_data: